build_now:              'YES'
min_system_version:     '10.7'
download_base_url:      'http://downloads.selfcontrolapp.com/'
web_base_url:           'https://selfcontrolapp.com'
appcast_basefolder:     '/Users/charlie/dev/selfcontrol/'
appcast_xml_name:       'SelfControlAppcast.xml'  
keychain_privkey_name:  'SelfControl Sparkle Private Key'
css_file_name:          'rnotes.css' 
